services:
  framework.host:
    image: framework.host
    build:
      context: .
      dockerfile: FrameWork.Host/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=framework-host
    networks:
      - elk

  elasticsearch:
    container_name: els
    image: elasticsearch:8.10.1
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch-data:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - elk
  
  kibana:
    container_name: kibana
    image: kibana:8.10.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin  # 添加用户名
      - ELASTICSEARCH_PASSWORD=123456  # 添加密码
    networks:
      - elk

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    ports:
      - 4317:4317 # For gRPC
      - 55681:55681 # For HTTP
      - 8888:8888   # For debugging
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - elk
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - elk
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - elk
volumes:
  grafana_data:
    
networks:
  elk:
    driver: bridge
  
    