services:
  framework.host:
    image: framework.host
    build:
      context: .
      dockerfile: FrameWork.Host/Dockerfile

  elasticsearch:
    container_name: els
    image: elasticsearch:8.10.1
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch-data:/var/lib/elasticsearch/data
    networks:
      - elk
    
  kibana:
    container_name: kibana
    image: kibana:8.10.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elk
  
networks:
  elk:
    driver: bridge
    