receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s

exporters:
  debug: {}
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    username: "admin"         # 添加用户名
    password: "abcdefg"        # 添加密码

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]