receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

processors:
  batch:  # 批量处理数据提升性能

exporters:
  debug:
    loglevel: debug
  prometheus:
    endpoint: "prometheus:9090"  # 导出指标到 Prometheus
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "app-logs"  # 日志索引名称

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]  # 导出追踪到 ES
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, elasticsearch]  # 导出指标到 Prometheus 和 ES
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]  # 导出日志到 ES