receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s

exporters:
  otlphttp:  # 使用 OTLP HTTP 导出器
    endpoint: "http://logstash:5044"  # Logstash 接收 OTLP 数据的端口
    compression: "gzip"  # 使用 gzip 压缩

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]