receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s

exporters:
  debug: {}
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "otel-logs"
    pipeline: "default-pipeline"
    username: "admin"         # 添加用户名
    password: "123456"        # 添加密码

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]